// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function LoadMD(arg1:string):Promise<string>;

export function SelectMarkdownFile():Promise<model.MDInfo>;
