// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadImgBase64(arg1, arg2) {
  return window['go']['main']['App']['LoadImgBase64'](arg1, arg2);
}

export function LoadMD(arg1) {
  return window['go']['main']['App']['LoadMD'](arg1);
}

export function SelectMarkdownFile() {
  return window['go']['main']['App']['SelectMarkdownFile']();
}
